# fly.toml app configuration file generated for blog-blue-grass-6004 on 2025-04-11T14:12:59+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-blue-grass-6004'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
